version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - db
    environment:
      PORT: 3000
      DATABASE_URL: postgres://postgres:postgres@db:5432/app
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules

volumes:
  pgdata: